CC = g++

1-5a:1-5a.cpp
	$(CC) 1-5a.cpp -o 1-5a

1-5b:1-5b.cpp
	$(CC) 1-5b.cpp -o 1-5b

1-6:1-6.cpp
	$(CC) 1-6.cpp -o 1-6

1-7:1-7.cpp
	$(CC) 1-7.cpp -o 1-7

1-8:1-8.cpp
	$(CC) 1-8.cpp -o 1-8

clean:
	rm 1-5*

